// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package heatingsystem.proxies;

public class Summary
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject summaryMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "HeatingSystem.Summary";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Base("Base"),
		Visibility("Visibility"),
		Dt("Dt"),
		Timezone("Timezone"),
		_id("_id"),
		Name("Name"),
		Cod("Cod"),
		Coord_Summary("HeatingSystem.Coord_Summary"),
		Weather_Summary("HeatingSystem.Weather_Summary"),
		Main_Summary("HeatingSystem.Main_Summary"),
		Wind_Summary("HeatingSystem.Wind_Summary"),
		Clouds_Summary("HeatingSystem.Clouds_Summary"),
		Sys_Summary("HeatingSystem.Sys_Summary");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Summary(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Summary(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject summaryMendixObject)
	{
		if (summaryMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, summaryMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.summaryMendixObject = summaryMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Summary.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static heatingsystem.proxies.Summary initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return heatingsystem.proxies.Summary.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static heatingsystem.proxies.Summary initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new heatingsystem.proxies.Summary(context, mendixObject);
	}

	public static heatingsystem.proxies.Summary load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return heatingsystem.proxies.Summary.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Base
	 */
	public final java.lang.String getBase()
	{
		return getBase(getContext());
	}

	/**
	 * @param context
	 * @return value of Base
	 */
	public final java.lang.String getBase(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Base.toString());
	}

	/**
	 * Set value of Base
	 * @param base
	 */
	public final void setBase(java.lang.String base)
	{
		setBase(getContext(), base);
	}

	/**
	 * Set value of Base
	 * @param context
	 * @param base
	 */
	public final void setBase(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String base)
	{
		getMendixObject().setValue(context, MemberNames.Base.toString(), base);
	}

	/**
	 * @return value of Visibility
	 */
	public final java.lang.Integer getVisibility()
	{
		return getVisibility(getContext());
	}

	/**
	 * @param context
	 * @return value of Visibility
	 */
	public final java.lang.Integer getVisibility(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Visibility.toString());
	}

	/**
	 * Set value of Visibility
	 * @param visibility
	 */
	public final void setVisibility(java.lang.Integer visibility)
	{
		setVisibility(getContext(), visibility);
	}

	/**
	 * Set value of Visibility
	 * @param context
	 * @param visibility
	 */
	public final void setVisibility(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer visibility)
	{
		getMendixObject().setValue(context, MemberNames.Visibility.toString(), visibility);
	}

	/**
	 * @return value of Dt
	 */
	public final java.lang.Integer getDt()
	{
		return getDt(getContext());
	}

	/**
	 * @param context
	 * @return value of Dt
	 */
	public final java.lang.Integer getDt(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Dt.toString());
	}

	/**
	 * Set value of Dt
	 * @param dt
	 */
	public final void setDt(java.lang.Integer dt)
	{
		setDt(getContext(), dt);
	}

	/**
	 * Set value of Dt
	 * @param context
	 * @param dt
	 */
	public final void setDt(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer dt)
	{
		getMendixObject().setValue(context, MemberNames.Dt.toString(), dt);
	}

	/**
	 * @return value of Timezone
	 */
	public final java.lang.Integer getTimezone()
	{
		return getTimezone(getContext());
	}

	/**
	 * @param context
	 * @return value of Timezone
	 */
	public final java.lang.Integer getTimezone(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Timezone.toString());
	}

	/**
	 * Set value of Timezone
	 * @param timezone
	 */
	public final void setTimezone(java.lang.Integer timezone)
	{
		setTimezone(getContext(), timezone);
	}

	/**
	 * Set value of Timezone
	 * @param context
	 * @param timezone
	 */
	public final void setTimezone(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer timezone)
	{
		getMendixObject().setValue(context, MemberNames.Timezone.toString(), timezone);
	}

	/**
	 * @return value of _id
	 */
	public final java.lang.Integer get_id()
	{
		return get_id(getContext());
	}

	/**
	 * @param context
	 * @return value of _id
	 */
	public final java.lang.Integer get_id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames._id.toString());
	}

	/**
	 * Set value of _id
	 * @param _id
	 */
	public final void set_id(java.lang.Integer _id)
	{
		set_id(getContext(), _id);
	}

	/**
	 * Set value of _id
	 * @param context
	 * @param _id
	 */
	public final void set_id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer _id)
	{
		getMendixObject().setValue(context, MemberNames._id.toString(), _id);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Cod
	 */
	public final java.lang.Integer getCod()
	{
		return getCod(getContext());
	}

	/**
	 * @param context
	 * @return value of Cod
	 */
	public final java.lang.Integer getCod(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Cod.toString());
	}

	/**
	 * Set value of Cod
	 * @param cod
	 */
	public final void setCod(java.lang.Integer cod)
	{
		setCod(getContext(), cod);
	}

	/**
	 * Set value of Cod
	 * @param context
	 * @param cod
	 */
	public final void setCod(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer cod)
	{
		getMendixObject().setValue(context, MemberNames.Cod.toString(), cod);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Coord_Summary
	 */
	public final heatingsystem.proxies.Coord getCoord_Summary() throws com.mendix.core.CoreException
	{
		return getCoord_Summary(getContext());
	}

	/**
	 * @param context
	 * @return value of Coord_Summary
	 * @throws com.mendix.core.CoreException
	 */
	public final heatingsystem.proxies.Coord getCoord_Summary(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		heatingsystem.proxies.Coord result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Coord_Summary.toString());
		if (identifier != null) {
			result = heatingsystem.proxies.Coord.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Coord_Summary
	 * @param coord_summary
	 */
	public final void setCoord_Summary(heatingsystem.proxies.Coord coord_summary)
	{
		setCoord_Summary(getContext(), coord_summary);
	}

	/**
	 * Set value of Coord_Summary
	 * @param context
	 * @param coord_summary
	 */
	public final void setCoord_Summary(com.mendix.systemwideinterfaces.core.IContext context, heatingsystem.proxies.Coord coord_summary)
	{
		if (coord_summary == null) {
			getMendixObject().setValue(context, MemberNames.Coord_Summary.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Coord_Summary.toString(), coord_summary.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Weather_Summary
	 */
	public final heatingsystem.proxies.Weather getWeather_Summary() throws com.mendix.core.CoreException
	{
		return getWeather_Summary(getContext());
	}

	/**
	 * @param context
	 * @return value of Weather_Summary
	 * @throws com.mendix.core.CoreException
	 */
	public final heatingsystem.proxies.Weather getWeather_Summary(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		heatingsystem.proxies.Weather result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Weather_Summary.toString());
		if (identifier != null) {
			result = heatingsystem.proxies.Weather.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Weather_Summary
	 * @param weather_summary
	 */
	public final void setWeather_Summary(heatingsystem.proxies.Weather weather_summary)
	{
		setWeather_Summary(getContext(), weather_summary);
	}

	/**
	 * Set value of Weather_Summary
	 * @param context
	 * @param weather_summary
	 */
	public final void setWeather_Summary(com.mendix.systemwideinterfaces.core.IContext context, heatingsystem.proxies.Weather weather_summary)
	{
		if (weather_summary == null) {
			getMendixObject().setValue(context, MemberNames.Weather_Summary.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Weather_Summary.toString(), weather_summary.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Main_Summary
	 */
	public final heatingsystem.proxies.Main getMain_Summary() throws com.mendix.core.CoreException
	{
		return getMain_Summary(getContext());
	}

	/**
	 * @param context
	 * @return value of Main_Summary
	 * @throws com.mendix.core.CoreException
	 */
	public final heatingsystem.proxies.Main getMain_Summary(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		heatingsystem.proxies.Main result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Main_Summary.toString());
		if (identifier != null) {
			result = heatingsystem.proxies.Main.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Main_Summary
	 * @param main_summary
	 */
	public final void setMain_Summary(heatingsystem.proxies.Main main_summary)
	{
		setMain_Summary(getContext(), main_summary);
	}

	/**
	 * Set value of Main_Summary
	 * @param context
	 * @param main_summary
	 */
	public final void setMain_Summary(com.mendix.systemwideinterfaces.core.IContext context, heatingsystem.proxies.Main main_summary)
	{
		if (main_summary == null) {
			getMendixObject().setValue(context, MemberNames.Main_Summary.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Main_Summary.toString(), main_summary.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Wind_Summary
	 */
	public final heatingsystem.proxies.Wind getWind_Summary() throws com.mendix.core.CoreException
	{
		return getWind_Summary(getContext());
	}

	/**
	 * @param context
	 * @return value of Wind_Summary
	 * @throws com.mendix.core.CoreException
	 */
	public final heatingsystem.proxies.Wind getWind_Summary(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		heatingsystem.proxies.Wind result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Wind_Summary.toString());
		if (identifier != null) {
			result = heatingsystem.proxies.Wind.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Wind_Summary
	 * @param wind_summary
	 */
	public final void setWind_Summary(heatingsystem.proxies.Wind wind_summary)
	{
		setWind_Summary(getContext(), wind_summary);
	}

	/**
	 * Set value of Wind_Summary
	 * @param context
	 * @param wind_summary
	 */
	public final void setWind_Summary(com.mendix.systemwideinterfaces.core.IContext context, heatingsystem.proxies.Wind wind_summary)
	{
		if (wind_summary == null) {
			getMendixObject().setValue(context, MemberNames.Wind_Summary.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Wind_Summary.toString(), wind_summary.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Clouds_Summary
	 */
	public final heatingsystem.proxies.Clouds getClouds_Summary() throws com.mendix.core.CoreException
	{
		return getClouds_Summary(getContext());
	}

	/**
	 * @param context
	 * @return value of Clouds_Summary
	 * @throws com.mendix.core.CoreException
	 */
	public final heatingsystem.proxies.Clouds getClouds_Summary(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		heatingsystem.proxies.Clouds result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Clouds_Summary.toString());
		if (identifier != null) {
			result = heatingsystem.proxies.Clouds.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Clouds_Summary
	 * @param clouds_summary
	 */
	public final void setClouds_Summary(heatingsystem.proxies.Clouds clouds_summary)
	{
		setClouds_Summary(getContext(), clouds_summary);
	}

	/**
	 * Set value of Clouds_Summary
	 * @param context
	 * @param clouds_summary
	 */
	public final void setClouds_Summary(com.mendix.systemwideinterfaces.core.IContext context, heatingsystem.proxies.Clouds clouds_summary)
	{
		if (clouds_summary == null) {
			getMendixObject().setValue(context, MemberNames.Clouds_Summary.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Clouds_Summary.toString(), clouds_summary.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Sys_Summary
	 */
	public final heatingsystem.proxies.Sys getSys_Summary() throws com.mendix.core.CoreException
	{
		return getSys_Summary(getContext());
	}

	/**
	 * @param context
	 * @return value of Sys_Summary
	 * @throws com.mendix.core.CoreException
	 */
	public final heatingsystem.proxies.Sys getSys_Summary(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		heatingsystem.proxies.Sys result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Sys_Summary.toString());
		if (identifier != null) {
			result = heatingsystem.proxies.Sys.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Sys_Summary
	 * @param sys_summary
	 */
	public final void setSys_Summary(heatingsystem.proxies.Sys sys_summary)
	{
		setSys_Summary(getContext(), sys_summary);
	}

	/**
	 * Set value of Sys_Summary
	 * @param context
	 * @param sys_summary
	 */
	public final void setSys_Summary(com.mendix.systemwideinterfaces.core.IContext context, heatingsystem.proxies.Sys sys_summary)
	{
		if (sys_summary == null) {
			getMendixObject().setValue(context, MemberNames.Sys_Summary.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Sys_Summary.toString(), sys_summary.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return summaryMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final heatingsystem.proxies.Summary that = (heatingsystem.proxies.Summary) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
