// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package heatingsystem.proxies;

public class Sys
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject sysMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "HeatingSystem.Sys";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		_type("_type"),
		_id("_id"),
		Country("Country"),
		Sunrise("Sunrise"),
		Sunset("Sunset"),
		Sys_Summary("HeatingSystem.Sys_Summary");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Sys(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Sys(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject sysMendixObject)
	{
		if (sysMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, sysMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.sysMendixObject = sysMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Sys.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static heatingsystem.proxies.Sys initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return heatingsystem.proxies.Sys.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static heatingsystem.proxies.Sys initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new heatingsystem.proxies.Sys(context, mendixObject);
	}

	public static heatingsystem.proxies.Sys load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return heatingsystem.proxies.Sys.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of _type
	 */
	public final java.lang.Integer get_type()
	{
		return get_type(getContext());
	}

	/**
	 * @param context
	 * @return value of _type
	 */
	public final java.lang.Integer get_type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames._type.toString());
	}

	/**
	 * Set value of _type
	 * @param _type
	 */
	public final void set_type(java.lang.Integer _type)
	{
		set_type(getContext(), _type);
	}

	/**
	 * Set value of _type
	 * @param context
	 * @param _type
	 */
	public final void set_type(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer _type)
	{
		getMendixObject().setValue(context, MemberNames._type.toString(), _type);
	}

	/**
	 * @return value of _id
	 */
	public final java.lang.Integer get_id()
	{
		return get_id(getContext());
	}

	/**
	 * @param context
	 * @return value of _id
	 */
	public final java.lang.Integer get_id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames._id.toString());
	}

	/**
	 * Set value of _id
	 * @param _id
	 */
	public final void set_id(java.lang.Integer _id)
	{
		set_id(getContext(), _id);
	}

	/**
	 * Set value of _id
	 * @param context
	 * @param _id
	 */
	public final void set_id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer _id)
	{
		getMendixObject().setValue(context, MemberNames._id.toString(), _id);
	}

	/**
	 * @return value of Country
	 */
	public final java.lang.String getCountry()
	{
		return getCountry(getContext());
	}

	/**
	 * @param context
	 * @return value of Country
	 */
	public final java.lang.String getCountry(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Country.toString());
	}

	/**
	 * Set value of Country
	 * @param country
	 */
	public final void setCountry(java.lang.String country)
	{
		setCountry(getContext(), country);
	}

	/**
	 * Set value of Country
	 * @param context
	 * @param country
	 */
	public final void setCountry(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String country)
	{
		getMendixObject().setValue(context, MemberNames.Country.toString(), country);
	}

	/**
	 * @return value of Sunrise
	 */
	public final java.lang.Integer getSunrise()
	{
		return getSunrise(getContext());
	}

	/**
	 * @param context
	 * @return value of Sunrise
	 */
	public final java.lang.Integer getSunrise(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Sunrise.toString());
	}

	/**
	 * Set value of Sunrise
	 * @param sunrise
	 */
	public final void setSunrise(java.lang.Integer sunrise)
	{
		setSunrise(getContext(), sunrise);
	}

	/**
	 * Set value of Sunrise
	 * @param context
	 * @param sunrise
	 */
	public final void setSunrise(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer sunrise)
	{
		getMendixObject().setValue(context, MemberNames.Sunrise.toString(), sunrise);
	}

	/**
	 * @return value of Sunset
	 */
	public final java.lang.Integer getSunset()
	{
		return getSunset(getContext());
	}

	/**
	 * @param context
	 * @return value of Sunset
	 */
	public final java.lang.Integer getSunset(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Sunset.toString());
	}

	/**
	 * Set value of Sunset
	 * @param sunset
	 */
	public final void setSunset(java.lang.Integer sunset)
	{
		setSunset(getContext(), sunset);
	}

	/**
	 * Set value of Sunset
	 * @param context
	 * @param sunset
	 */
	public final void setSunset(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer sunset)
	{
		getMendixObject().setValue(context, MemberNames.Sunset.toString(), sunset);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Sys_Summary
	 */
	public final heatingsystem.proxies.Summary getSys_Summary() throws com.mendix.core.CoreException
	{
		return getSys_Summary(getContext());
	}

	/**
	 * @param context
	 * @return value of Sys_Summary
	 * @throws com.mendix.core.CoreException
	 */
	public final heatingsystem.proxies.Summary getSys_Summary(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		heatingsystem.proxies.Summary result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Sys_Summary.toString());
		if (identifier != null) {
			result = heatingsystem.proxies.Summary.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Sys_Summary
	 * @param sys_summary
	 */
	public final void setSys_Summary(heatingsystem.proxies.Summary sys_summary)
	{
		setSys_Summary(getContext(), sys_summary);
	}

	/**
	 * Set value of Sys_Summary
	 * @param context
	 * @param sys_summary
	 */
	public final void setSys_Summary(com.mendix.systemwideinterfaces.core.IContext context, heatingsystem.proxies.Summary sys_summary)
	{
		if (sys_summary == null) {
			getMendixObject().setValue(context, MemberNames.Sys_Summary.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Sys_Summary.toString(), sys_summary.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return sysMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final heatingsystem.proxies.Sys that = (heatingsystem.proxies.Sys) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
