// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package heatingsystem.proxies;

public class TechnicianTask
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject technicianTaskMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "HeatingSystem.TechnicianTask";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Comment("Comment"),
		Completed("Completed"),
		TechnicianTask_ServiceRequest("HeatingSystem.TechnicianTask_ServiceRequest");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TechnicianTask(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected TechnicianTask(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject technicianTaskMendixObject)
	{
		if (technicianTaskMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, technicianTaskMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.technicianTaskMendixObject = technicianTaskMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'TechnicianTask.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static heatingsystem.proxies.TechnicianTask initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return heatingsystem.proxies.TechnicianTask.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static heatingsystem.proxies.TechnicianTask initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new heatingsystem.proxies.TechnicianTask(context, mendixObject);
	}

	public static heatingsystem.proxies.TechnicianTask load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return heatingsystem.proxies.TechnicianTask.initialize(context, mendixObject);
	}

	public static java.util.List<heatingsystem.proxies.TechnicianTask> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> heatingsystem.proxies.TechnicianTask.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Comment
	 */
	public final java.lang.String getComment()
	{
		return getComment(getContext());
	}

	/**
	 * @param context
	 * @return value of Comment
	 */
	public final java.lang.String getComment(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Comment.toString());
	}

	/**
	 * Set value of Comment
	 * @param comment
	 */
	public final void setComment(java.lang.String comment)
	{
		setComment(getContext(), comment);
	}

	/**
	 * Set value of Comment
	 * @param context
	 * @param comment
	 */
	public final void setComment(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String comment)
	{
		getMendixObject().setValue(context, MemberNames.Comment.toString(), comment);
	}

	/**
	 * @return value of Completed
	 */
	public final java.lang.Boolean getCompleted()
	{
		return getCompleted(getContext());
	}

	/**
	 * @param context
	 * @return value of Completed
	 */
	public final java.lang.Boolean getCompleted(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Completed.toString());
	}

	/**
	 * Set value of Completed
	 * @param completed
	 */
	public final void setCompleted(java.lang.Boolean completed)
	{
		setCompleted(getContext(), completed);
	}

	/**
	 * Set value of Completed
	 * @param context
	 * @param completed
	 */
	public final void setCompleted(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean completed)
	{
		getMendixObject().setValue(context, MemberNames.Completed.toString(), completed);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TechnicianTask_ServiceRequest
	 */
	public final heatingsystem.proxies.ServiceRequest getTechnicianTask_ServiceRequest() throws com.mendix.core.CoreException
	{
		return getTechnicianTask_ServiceRequest(getContext());
	}

	/**
	 * @param context
	 * @return value of TechnicianTask_ServiceRequest
	 * @throws com.mendix.core.CoreException
	 */
	public final heatingsystem.proxies.ServiceRequest getTechnicianTask_ServiceRequest(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		heatingsystem.proxies.ServiceRequest result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TechnicianTask_ServiceRequest.toString());
		if (identifier != null) {
			result = heatingsystem.proxies.ServiceRequest.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TechnicianTask_ServiceRequest
	 * @param techniciantask_servicerequest
	 */
	public final void setTechnicianTask_ServiceRequest(heatingsystem.proxies.ServiceRequest techniciantask_servicerequest)
	{
		setTechnicianTask_ServiceRequest(getContext(), techniciantask_servicerequest);
	}

	/**
	 * Set value of TechnicianTask_ServiceRequest
	 * @param context
	 * @param techniciantask_servicerequest
	 */
	public final void setTechnicianTask_ServiceRequest(com.mendix.systemwideinterfaces.core.IContext context, heatingsystem.proxies.ServiceRequest techniciantask_servicerequest)
	{
		if (techniciantask_servicerequest == null) {
			getMendixObject().setValue(context, MemberNames.TechnicianTask_ServiceRequest.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TechnicianTask_ServiceRequest.toString(), techniciantask_servicerequest.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return technicianTaskMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final heatingsystem.proxies.TechnicianTask that = (heatingsystem.proxies.TechnicianTask) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
